from __future__ import annotations

"""Minimal real-provider probe.

These tests invoke real provider CLIs and external APIs. They are skipped by
default and intended for release-profile verification, not fast feedback. The
probe intentionally stays small: deterministic contract checks cover Loopora
semantics with fake executors; this real probe only proves that a real provider
can execute Loopora's frozen role request, return structured output, persist
artifacts, and resume a step session across rounds.
"""

import json
import os
import shutil
import time
from dataclasses import dataclass
from pathlib import Path

import pytest

from loopora.bundles import bundle_to_yaml
from loopora.db import LooporaRepository
from loopora.event_redaction import redact_sensitive_value
from loopora.providers import executor_profile, normalize_executor_kind
from loopora.service import LooporaService
from loopora.settings import AppSettings
from loopora.workflows import builtin_prompt_markdown

REAL_CLI_ENV = "LOOPORA_ENABLE_REAL_CLI_PROBE"
REAL_CLI_TIMEOUT_ENV = "LOOPORA_REAL_CLI_TIMEOUT_SECONDS"
REAL_CLI_TARGETS_ENV = "LOOPORA_REAL_CLI_TARGETS"
REAL_CLI_CODEX_MODEL_ENV = "LOOPORA_REAL_CLI_CODEX_MODEL"
REAL_CLI_CLAUDE_MODEL_ENV = "LOOPORA_REAL_CLI_CLAUDE_MODEL"
REAL_CLI_OPENCODE_MODEL_ENV = "LOOPORA_REAL_CLI_OPENCODE_MODEL"
REAL_PROBE_MODEL_OVERRIDE_ENV = "LOOPORA_REAL_PROBE_ALLOW_MODEL_OVERRIDE"
PROVIDER_ORDER = ("codex", "claude", "opencode")
PROVIDER_MODEL_ENV = {
    "codex": REAL_CLI_CODEX_MODEL_ENV,
    "claude": REAL_CLI_CLAUDE_MODEL_ENV,
    "opencode": REAL_CLI_OPENCODE_MODEL_ENV,
}
MARKER_FILE = "loopora-real-cli-marker.txt"
MARKER_TEXT = "Loopora real CLI smoke marker. Do not edit this file.\n"


@dataclass(frozen=True)
class RealRunArtifacts:
    provider: str
    workdir: Path
    run: dict
    run_dir: Path
    events: list[dict]
    role_requests: list[dict]
    command_events: list[dict]
    terminal_event: dict


@dataclass(frozen=True)
class RealCliPhaseReportInput:
    provider: str
    workdir: Path
    model: str
    run: dict | None
    artifacts: RealRunArtifacts | None
    error: object | None = None


def _read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _truncate_text(value: object, *, limit: int = 500) -> str:
    text = str(value or "")
    if len(text) <= limit:
        return text
    return text[: limit - 3] + "..."


def _wait_for_terminal_run(service: LooporaService, run_id: str, *, timeout_seconds: float) -> dict:
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        run = service.get_run(run_id)
        if run["status"] in {"succeeded", "failed", "stopped"}:
            return run
        time.sleep(1.0)
    raise AssertionError(f"timed out waiting for real CLI run {run_id} to finish")


def _selected_real_cli_targets() -> tuple[str, ...]:
    raw = str(os.environ.get(REAL_CLI_TARGETS_ENV, "") or "").strip()
    if not raw:
        return tuple(provider for provider in PROVIDER_ORDER if shutil.which(executor_profile(provider).cli_name) is not None)

    selected: list[str] = []
    invalid: list[str] = []
    for token in raw.split(","):
        stripped = token.strip()
        if not stripped:
            continue
        try:
            normalized = normalize_executor_kind(stripped)
        except ValueError:
            invalid.append(stripped)
            continue
        if normalized not in PROVIDER_ORDER:
            invalid.append(stripped)
            continue
        if normalized not in selected:
            selected.append(normalized)

    if invalid:
        joined = ", ".join(invalid)
        raise AssertionError(f"unsupported {REAL_CLI_TARGETS_ENV} entries: {joined}")
    return tuple(selected)


def _require_real_cli_target(provider: str) -> None:
    if os.environ.get(REAL_CLI_ENV) != "1":
        pytest.skip(f"set {REAL_CLI_ENV}=1 to run the real-provider release-profile probe")

    cli_name = executor_profile(provider).cli_name
    selected = _selected_real_cli_targets()
    if provider not in selected:
        if shutil.which(cli_name) is None:
            pytest.skip(f"{provider} CLI ({cli_name}) is unavailable in PATH")
        pytest.skip(f"{provider} is not enabled by {REAL_CLI_TARGETS_ENV}")


def _provider_model(provider: str) -> str:
    env_name = PROVIDER_MODEL_ENV[provider]
    override = str(os.environ.get(env_name, "") or "").strip()
    if override:
        return override
    return executor_profile(provider).default_model


def _model_override_allowed() -> bool:
    return os.environ.get(REAL_PROBE_MODEL_OVERRIDE_ENV) == "1"


def _assert_real_cli_model_policy(provider: str, model: str) -> None:
    if provider == "codex":
        return
    expected = executor_profile(provider).default_model
    if model == expected:
        return
    assert _model_override_allowed(), (
        f"{provider} real-cli probe must use default model {expected!r} on the release path; "
        f"got {model!r}. Set {REAL_PROBE_MODEL_OVERRIDE_ENV}=1 only for an intentional override validation."
    )


def _provider_reasoning_effort(provider: str) -> str:
    return executor_profile(provider).effort_default


def _summary_text(run_dir: Path) -> str:
    summary_path = run_dir / "summary.md"
    if not summary_path.exists():
        return "(missing summary.md)"
    return summary_path.read_text(encoding="utf-8")


def _safe_read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _real_service(tmp_path: Path, *, provider: str) -> LooporaService:
    repository = LooporaRepository(tmp_path / f"{provider}-minimal-real-cli.db")
    settings = AppSettings(
        max_concurrent_runs=1,
        polling_interval_seconds=0.1,
        stop_grace_period_seconds=0.5,
        role_idle_timeout_seconds=300.0,
    )
    return LooporaService(repository=repository, settings=settings)


def _create_minimal_workspace(tmp_path: Path, *, provider: str) -> Path:
    _require_real_cli_target(provider)
    workdir = tmp_path / f"{provider}-minimal-real-cli-workspace"
    workdir.mkdir()
    (workdir / "README.md").write_text(
        "# Loopora real CLI smoke\n\nThis workspace is intentionally tiny.\n",
        encoding="utf-8",
    )
    (workdir / MARKER_FILE).write_text(MARKER_TEXT, encoding="utf-8")
    return workdir


def _minimal_real_cli_bundle_yaml(workdir: Path, *, provider: str) -> str:
    model = _provider_model(provider)
    reasoning_effort = _provider_reasoning_effort(provider)
    role_execution = {
        "executor_kind": provider,
        "executor_mode": "preset",
        "command_cli": "",
        "command_args_text": "",
        "model": model,
        "reasoning_effort": reasoning_effort,
    }
    bundle = {
        "version": 1,
        "metadata": {
            "name": f"Real CLI Minimal Smoke {provider}",
            "description": "Minimal real-provider release-profile probe.",
        },
        "collaboration_summary": (
            "Verify that Loopora can hand a frozen role request to a real provider CLI, "
            "parse structured output, persist artifacts, and resume the same step on the next round."
        ),
        "loop": {
            "name": f"Real CLI Minimal Smoke {provider}",
            "workdir": str(workdir.resolve()),
            "completion_mode": "rounds",
            "executor_kind": provider,
            "executor_mode": "preset",
            "command_cli": "",
            "command_args_text": "",
            "model": model,
            "reasoning_effort": reasoning_effort,
            "iteration_interval_seconds": 0,
            "max_iters": 2,
            "max_role_retries": 1,
            "delta_threshold": 0.005,
            "trigger_window": 2,
            "regression_window": 2,
        },
        "spec": {
            "markdown": f"""# Task

Inspect this tiny workspace and report that the provider adapter can see `{MARKER_FILE}`.

# Done When

- The role output mentions that `{MARKER_FILE}` exists.
- No file changes are required.

# Guardrails

- Do not edit files.
- Keep the response concise and structured.

# Evidence Preferences

- Prefer direct filesystem observation over guesses.
""",
        },
        "role_definitions": [
            {
                "key": "builder",
                "name": "Real CLI Smoke Builder",
                "description": "Inspects a tiny workspace without changing it.",
                "archetype": "builder",
                "prompt_ref": "builder.md",
                "prompt_markdown": builtin_prompt_markdown("builder.md"),
                "posture_notes": (
                    f"Confirm `{MARKER_FILE}` exists and explicitly avoid modifying files. This is a provider-adapter smoke test, not a product-quality task."
                ),
                **role_execution,
            },
        ],
        "workflow": {
            "version": 1,
            "preset": "custom",
            "collaboration_intent": "Run one Builder step for two rounds to prove real CLI execution and session resume.",
            "roles": [{"id": "builder", "role_definition_key": "builder"}],
            "steps": [{"id": "builder_step", "role_id": "builder", "inherit_session": True}],
        },
    }
    return bundle_to_yaml(bundle)


def _collect_artifacts(provider: str, workdir: Path, run: dict) -> RealRunArtifacts:
    run_dir = Path(run["runs_dir"])
    events = _read_jsonl(run_dir / "timeline" / "events.jsonl")
    role_requests = _read_jsonl(run_dir / "context" / "role_requests.jsonl")
    command_events = [event for event in events if event["event_type"] == "codex_event" and event.get("payload", {}).get("type") == "command"]
    terminal_event = next(event for event in reversed(events) if event["event_type"] == "run_finished")
    return RealRunArtifacts(
        provider=provider,
        workdir=workdir,
        run=run,
        run_dir=run_dir,
        events=events,
        role_requests=role_requests,
        command_events=command_events,
        terminal_event=terminal_event,
    )


def _command_messages(artifacts: RealRunArtifacts) -> list[str]:
    return [str(event.get("payload", {}).get("message") or "") for event in artifacts.command_events]


def _requests_for_step(artifacts: RealRunArtifacts, step_id: str) -> list[dict]:
    return [item for item in artifacts.role_requests if item.get("step_id") == step_id]


def _role_execution_summaries(artifacts: RealRunArtifacts) -> list[dict]:
    return [event for event in artifacts.events if event["event_type"] == "role_execution_summary" and event.get("role") == "generator"]


def _provider_resume_command_shape_result(artifacts: RealRunArtifacts) -> dict:
    messages = _command_messages(artifacts)
    if artifacts.provider == "codex":
        resume_messages = [message for message in messages if "codex exec resume" in message]
        invalid_flags = [flag for flag in ("--cd", "--sandbox", "--output-schema") if any(flag in message for message in resume_messages)]
        return {"ok": bool(resume_messages) and not invalid_flags, "resume_messages": resume_messages[:3], "invalid_flags": invalid_flags}
    if artifacts.provider == "claude":
        resume_messages = [message for message in messages if message.startswith("claude ") and " --resume " in f" {message} "]
        invalid_flags = ["--continue"] if any(" --continue " in f" {message} " for message in resume_messages) else []
        return {"ok": bool(resume_messages) and not invalid_flags, "resume_messages": resume_messages[:3], "invalid_flags": invalid_flags}
    resume_messages = [message for message in messages if message.startswith("opencode run") and " --session " in f" {message} "]
    invalid_flags = ["--continue"] if any(" --continue " in f" {message} " for message in resume_messages) else []
    return {"ok": bool(resume_messages) and not invalid_flags, "resume_messages": resume_messages[:3], "invalid_flags": invalid_flags}


def _assert_provider_resume_command_shape(artifacts: RealRunArtifacts) -> None:
    result = _provider_resume_command_shape_result(artifacts)
    assert result["resume_messages"], f"expected a {artifacts.provider} resume command in the second builder iteration"
    assert result["ok"], result


def _assert_real_cli_model_observed(artifacts: RealRunArtifacts, model: str) -> None:
    if artifacts.provider == "codex":
        return
    messages = _command_messages(artifacts)
    assert any(model in message for message in messages), (
        f"expected real {artifacts.provider} command events to include selected model {model!r}; messages={messages[:3]}"
    )


def _phase_report_path(workdir: Path) -> Path:
    return workdir / ".loopora" / "real-probes" / "real-cli-phase-report.json"


def _command_event_summaries(artifacts: RealRunArtifacts | None) -> list[dict]:
    if artifacts is None:
        return []
    return [
        {
            "event_id": event.get("id"),
            "message": _truncate_text((event.get("payload") or {}).get("message"), limit=360),
        }
        for event in artifacts.command_events[-6:]
    ]


def _role_request_summaries(artifacts: RealRunArtifacts | None) -> list[dict]:
    if artifacts is None:
        return []
    return [
        {
            "step_id": item.get("step_id"),
            "role_id": item.get("role_id"),
            "resume_session_id": bool(item.get("resume_session_id")),
        }
        for item in artifacts.role_requests[-6:]
    ]


def _build_real_cli_phase_report(inputs: RealCliPhaseReportInput) -> dict:
    provider = inputs.provider
    model = inputs.model
    run = inputs.run
    artifacts = inputs.artifacts
    expected_model = executor_profile(provider).default_model
    builder_requests = _requests_for_step(artifacts, "builder_step") if artifacts is not None else []
    resume_result = _provider_resume_command_shape_result(artifacts) if artifacts is not None else {"ok": False, "resume_messages": [], "invalid_flags": []}
    run_dir_value = str((run or {}).get("runs_dir") or "")
    run_dir = artifacts.run_dir if artifacts is not None else (Path(run_dir_value) if run_dir_value else None)
    return {
        "schema_version": 1,
        "provider": provider,
        "workdir": str(inputs.workdir),
        "selected_model": model,
        "expected_default_model": expected_model,
        "model_override_allowed": _model_override_allowed(),
        "phase_statuses": {
            "model_policy": {"ok": provider == "codex" or model == expected_model or _model_override_allowed()},
            "run_finished": {"ok": bool(artifacts and artifacts.terminal_event["payload"].get("status") == "succeeded")},
            "structured_output_observed": {"ok": bool(artifacts and _role_execution_summaries(artifacts))},
            "artifacts_persisted": {"ok": run_dir is not None and (run_dir / "summary.md").exists() and (run_dir / "contract" / "run_contract.json").exists()},
            "resume_session_observed": {"ok": len(builder_requests) >= 2 and bool(builder_requests[1].get("resume_session_id"))},
            "resume_command_shape_observed": {"ok": bool(resume_result.get("ok"))},
            "model_observed": {
                "ok": provider == "codex" or bool(artifacts and any(model in message for message in _command_messages(artifacts))),
            },
        },
        "diagnostics": {
            "run": {
                "id": (run or {}).get("id"),
                "status": (run or {}).get("status"),
                "runs_dir": str((run or {}).get("runs_dir") or ""),
            },
            "terminal_event": artifacts.terminal_event if artifacts is not None else {},
            "command_events": _command_event_summaries(artifacts),
            "role_requests": _role_request_summaries(artifacts),
            "resume_command_shape": resume_result,
            "artifacts": {
                "summary": str(run_dir / "summary.md") if run_dir is not None else "",
                "summary_exists": run_dir is not None and (run_dir / "summary.md").exists(),
                "run_contract": str(run_dir / "contract" / "run_contract.json") if run_dir is not None else "",
                "run_contract_exists": run_dir is not None and (run_dir / "contract" / "run_contract.json").exists(),
                "task_verdict": _safe_read_json(run_dir / "evidence" / "task_verdict.json") if run_dir is not None else {},
            },
            "error": _truncate_text(inputs.error, limit=700) if inputs.error is not None else "",
        },
    }


def _write_real_cli_phase_report(inputs: RealCliPhaseReportInput) -> tuple[dict, Path]:
    raw_report = _build_real_cli_phase_report(inputs)
    report = redact_sensitive_value("", raw_report)
    if not isinstance(report, dict):
        report = {}
    path = _phase_report_path(inputs.workdir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return report, path


def _format_real_cli_diagnostic_failure(message: object, *, report: dict, report_path: Path) -> str:
    compact = {
        "provider": report.get("provider"),
        "selected_model": report.get("selected_model"),
        "expected_default_model": report.get("expected_default_model"),
        "model_override_allowed": report.get("model_override_allowed"),
        "phase_statuses": report.get("phase_statuses"),
        "run": (report.get("diagnostics") or {}).get("run"),
        "resume_command_shape": (report.get("diagnostics") or {}).get("resume_command_shape"),
        "command_events": (report.get("diagnostics") or {}).get("command_events"),
    }
    return f"{message}\n\nReal probe phase report: {report_path}\n{json.dumps(compact, ensure_ascii=False, indent=2)}"


@pytest.mark.real_cli
@pytest.mark.parametrize("provider", PROVIDER_ORDER)
def test_real_cli_provider_adapter_minimal_bundle_runs_and_resumes(tmp_path: Path, provider: str) -> None:
    workdir = _create_minimal_workspace(tmp_path, provider=provider)
    service = _real_service(tmp_path, provider=provider)
    timeout_seconds = float(os.environ.get(REAL_CLI_TIMEOUT_ENV, "600"))
    model = _provider_model(provider)
    queued_run: dict | None = None
    final_run: dict | None = None
    artifacts: RealRunArtifacts | None = None

    try:
        _assert_real_cli_model_policy(provider, model)
        bundle_yaml = _minimal_real_cli_bundle_yaml(workdir, provider=provider)

        preview = service.preview_bundle_text(bundle_yaml)
        assert preview["ok"] is True
        assert preview["bundle"]["loop"]["workdir"] == str(workdir.resolve())
        bundle = service.import_bundle_text(bundle_yaml)
        assert bundle["loop_id"]

        queued_run = service.start_run(bundle["loop_id"])
        service.start_run_async(queued_run["id"])
        final_run = _wait_for_terminal_run(service, queued_run["id"], timeout_seconds=timeout_seconds)
        final_summary = _summary_text(Path(final_run["runs_dir"]))
        assert final_run["status"] == "succeeded", final_summary
        artifacts = _collect_artifacts(provider, workdir, final_run)
        _write_real_cli_phase_report(RealCliPhaseReportInput(provider=provider, workdir=workdir, model=model, run=final_run, artifacts=artifacts))
        summary = _summary_text(artifacts.run_dir)

        assert artifacts.terminal_event["payload"]["status"] == "succeeded", summary
        assert artifacts.terminal_event["payload"].get("reason") == "rounds_completed", summary
        assert not any(event["event_type"] == "run_aborted" for event in artifacts.events), summary
        assert (artifacts.run_dir / "summary.md").exists()
        assert (artifacts.run_dir / "contract" / "run_contract.json").exists()
        assert (workdir / MARKER_FILE).read_text(encoding="utf-8") == MARKER_TEXT

        builder_requests = _requests_for_step(artifacts, "builder_step")
        assert len(builder_requests) >= 2, summary
        assert builder_requests[0]["resume_session_id"] == ""
        assert builder_requests[1]["resume_session_id"]
        assert len(_role_execution_summaries(artifacts)) >= 2, summary
        assert not any("unexpected argument '--cd'" in message for message in _command_messages(artifacts))
        _assert_real_cli_model_observed(artifacts, model)
        _assert_provider_resume_command_shape(artifacts)
    except AssertionError as exc:
        report, report_path = _write_real_cli_phase_report(
            RealCliPhaseReportInput(provider=provider, workdir=workdir, model=model, run=final_run or queued_run, artifacts=artifacts, error=exc)
        )
        raise AssertionError(_format_real_cli_diagnostic_failure(exc, report=report, report_path=report_path)) from None
